const lessonData = [
    {
        title: "Lesson 1: Antonyms",
        instr: "Choose the opposite word.",
        qs: [
            { q: "Opposite of <u>hot</u>", opts: ["warm", "cold", "sunny", "burn"], c: 1 },
            { q: "Opposite of <u>big</u>", opts: ["large", "huge", "small", "tall"], c: 2 },
            { q: "Opposite of <u>happy</u>", opts: ["glad", "sad", "silly", "fun"], c: 1 },
            { q: "Opposite of <u>fast</u>", opts: ["quick", "slow", "run", "race"], c: 1 },
            { q: "Opposite of <u>up</u>", opts: ["high", "top", "down", "over"], c: 2 },
            { q: "Opposite of <u>in</u>", opts: ["out", "into", "inside", "on"], c: 0 },
            { q: "Opposite of <u>left</u>", opts: ["wrong", "right", "back", "side"], c: 1 },
            { q: "Opposite of <u>dark</u>", opts: ["black", "night", "light", "dim"], c: 2 },
            { q: "Opposite of <u>push</u>", opts: ["shove", "pull", "kick", "move"], c: 1 },
            { q: "Opposite of <u>open</u>", opts: ["shut", "door", "wide", "start"], c: 0 },
            { q: "Opposite of <u>empty</u>", opts: ["full", "glass", "gone", "nothing"], c: 0 },
            { q: "Opposite of <u>heavy</u>", opts: ["light", "weight", "hard", "soft"], c: 0 },
            { q: "Opposite of <u>wet</u>", opts: ["water", "dry", "rain", "damp"], c: 1 },
            { q: "Opposite of <u>clean</u>", opts: ["neat", "dirty", "wash", "new"], c: 1 },
            { q: "Opposite of <u>soft</u>", opts: ["hard", "pillow", "gentle", "smooth"], c: 0 },
            { q: "Opposite of <u>win</u>", opts: ["lose", "game", "first", "play"], c: 0 },
            { q: "Opposite of <u>young</u>", opts: ["baby", "old", "new", "kid"], c: 1 },
            { q: "Opposite of <u>short</u>", opts: ["small", "long", "tiny", "little"], c: 1 },
            { q: "Opposite of <u>above</u>", opts: ["over", "below", "high", "near"], c: 1 },
            { q: "Opposite of <u>early</u>", opts: ["late", "morning", "soon", "fast"], c: 0 },
            { q: "Opposite of <u>quiet</u>", opts: ["silent", "noisy", "calm", "still"], c: 1 },
            { q: "Opposite of <u>true</u>", opts: ["real", "false", "right", "yes"], c: 1 },
            { q: "Opposite of <u>give</u>", opts: ["take", "hand", "send", "present"], c: 0 },
            { q: "Opposite of <u>laugh</u>", opts: ["smile", "cry", "giggle", "joke"], c: 1 },
            { q: "Opposite of <u>brave</u>", opts: ["strong", "scared", "bold", "hero"], c: 1 },
            { q: "Opposite of <u>thick</u>", opts: ["wide", "thin", "heavy", "fat"], c: 1 },
            { q: "Opposite of <u>front</u>", opts: ["side", "back", "top", "first"], c: 1 },
            { q: "Opposite of <u>sharp</u>", opts: ["pointy", "dull", "knife", "edge"], c: 1 },
            { q: "Opposite of <u>easy</u>", opts: ["simple", "hard", "fun", "quick"], c: 1 },
            { q: "Opposite of <u>near</u>", opts: ["far", "close", "next", "here"], c: 0 },
            { q: "Opposite of <u>start</u>", opts: ["begin", "finish", "go", "ready"], c: 1 },
            { q: "Opposite of <u>boy</u>", opts: ["man", "girl", "child", "friend"], c: 1 }
        ]
    },
    {
        title: "Lesson 2: Synonyms",
        instr: "Choose the word with the same meaning.",
        qs: [
            { q: "Synonym of <u>small</u>", opts: ["big", "tiny", "large", "huge"], c: 1 },
            { q: "Synonym of <u>fast</u>", opts: ["slow", "quick", "lazy", "crawl"], c: 1 },
            { q: "Synonym of <u>glad</u>", opts: ["sad", "mad", "happy", "grumpy"], c: 2 },
            { q: "Synonym of <u>scared</u>", opts: ["brave", "afraid", "happy", "bold"], c: 1 },
            { q: "Synonym of <u>angry</u>", opts: ["mad", "calm", "cool", "nice"], c: 0 },
            { q: "Synonym of <u>neat</u>", opts: ["tidy", "messy", "dirty", "lost"], c: 0 },
            { q: "Synonym of <u>gift</u>", opts: ["box", "present", "toy", "card"], c: 1 },
            { q: "Synonym of <u>yell</u>", opts: ["whisper", "shout", "talk", "sing"], c: 1 },
            { q: "Synonym of <u>simple</u>", opts: ["hard", "easy", "rough", "tough"], c: 1 },
            { q: "Synonym of <u>silent</u>", opts: ["loud", "quiet", "noisy", "sound"], c: 1 },
            { q: "Synonym of <u>cold</u>", opts: ["hot", "chilly", "warm", "sunny"], c: 1 },
            { q: "Synonym of <u>start</u>", opts: ["stop", "begin", "end", "finish"], c: 1 },
            { q: "Synonym of <u>smart</u>", opts: ["dumb", "clever", "silly", "slow"], c: 1 },
            { q: "Synonym of <u>large</u>", opts: ["tiny", "huge", "small", "thin"], c: 1 },
            { q: "Synonym of <u>rock</u>", opts: ["sand", "stone", "water", "tree"], c: 1 },
            { q: "Synonym of <u>center</u>", opts: ["middle", "edge", "side", "back"], c: 0 },
            { q: "Synonym of <u>friend</u>", opts: ["enemy", "buddy", "stranger", "foe"], c: 1 },
            { q: "Synonym of <u>ill</u>", opts: ["well", "sick", "healthy", "strong"], c: 1 },
            { q: "Synonym of <u>tasty</u>", opts: ["bad", "yummy", "gross", "bitter"], c: 1 },
            { q: "Synonym of <u>leap</u>", opts: ["run", "jump", "walk", "sit"], c: 1 },
            { q: "Synonym of <u>correct</u>", opts: ["wrong", "right", "bad", "false"], c: 1 },
            { q: "Synonym of <u>help</u>", opts: ["hinder", "aid", "hurt", "stop"], c: 1 },
            { q: "Synonym of <u>sleepy</u>", opts: ["awake", "tired", "busy", "energetic"], c: 1 },
            { q: "Synonym of <u>broad</u>", opts: ["narrow", "wide", "thin", "short"], c: 1 },
            { q: "Synonym of <u>rich</u>", opts: ["poor", "wealthy", "needy", "low"], c: 1 },
            { q: "Synonym of <u>choose</u>", opts: ["take", "select", "lose", "keep"], c: 1 },
            { q: "Synonym of <u>ocean</u>", opts: ["lake", "sea", "river", "pond"], c: 1 },
            { q: "Synonym of <u>couch</u>", opts: ["sofa", "chair", "bed", "table"], c: 0 },
            { q: "Synonym of <u>trash</u>", opts: ["food", "garbage", "clean", "stuff"], c: 1 },
            { q: "Synonym of <u>above</u>", opts: ["below", "over", "under", "beside"], c: 1 },
            { q: "Synonym of <u>road</u>", opts: ["grass", "street", "house", "field"], c: 1 },
            { q: "Synonym of <u>child</u>", opts: ["adult", "kid", "man", "woman"], c: 1 }
        ]
    },
    {
        title: "Lesson 3: Homographs",
        instr: "One word, two meanings!",
        qs: [
            { q: "I have a ___ of gum. / Help me ___ my bag.", opts: ["pack", "stick", "roll", "box"], c: 1 },
            { q: "Turn on the ___ to cool down. / I am a big ___ of that team.", opts: ["air", "fan", "wind", "player"], c: 1 },
            { q: "Look at your ___ to see the time. / I like to ___ movies.", opts: ["clock", "watch", "show", "screen"], c: 1 },
            { q: "The bird has a sharp ___. / Please pay the ___.", opts: ["beak", "bill", "wing", "check"], c: 1 },
            { q: "The tree has thick ___. / The dog will ___ at the mailman.", opts: ["bark", "leaf", "root", "wood"], c: 0 },
            { q: "A flying ___ lives in a cave. / Hit the ball with a baseball ___.", opts: ["bird", "bat", "plane", "bug"], c: 1 },
            { q: "I wore a red ___ in my hair. / Please ___ down to the queen.", opts: ["tie", "bow", "hat", "ribbon"], c: 1 },
            { q: "The ___ of the wave was high. / Wash your hands in the ___.", opts: ["water", "sink", "boat", "towel"], c: 1 },
            { q: "I have a gold ___ on my finger. / Did the telephone ___?", opts: ["bell", "ring", "band", "call"], c: 1 },
            { q: "The ocean ___ hit the sand. / Please ___ goodbye to me.", opts: ["wave", "tide", "hand", "water"], c: 0 },
            { q: "A turtle can hide in its ___. / Put the sea ___ next to your ear.", opts: ["house", "shell", "skin", "back"], c: 1 },
            { q: "I will write with my ___ hand. / You got the answer ___.", opts: ["left", "right", "good", "best"], c: 1 },
            { q: "I will ___ the letter today. / The ___ of the ship is strong.", opts: ["post", "mail", "send", "box"], c: 1 },
            { q: "A duck has a flat ___. / Please pay the ___.", opts: ["bill", "beak", "mouth", "nose"], c: 0 },
            { q: "The ___ is green in the park. / The ___ is open from 9 to 5.", opts: ["grass", "bank", "river", "store"], c: 1 },
            { q: "I found a ___ on the beach. / ___ the nuts for the cake.", opts: ["shell", "rock", "crack", "sand"], c: 2 },
            { q: "The light is too ___. / You are a ___ student.", opts: ["bright", "shiny", "smart", "white"], c: 0 },
            { q: "Put a ___ on the letter. / The horses ___ their feet.", opts: ["seal", "stamp", "mark", "sticker"], c: 1 },
            { q: "The ___ are in the sky. / I love to ___ movies.", opts: ["sun", "star", "moon", "cloud"], c: 1 },
            { q: "A ___ of matches. / They wear a ___ing outfit.", opts: ["box", "match", "pair", "set"], c: 1 },
            { q: "I can ___ the music. / The ___ is a baby deer.", opts: ["hear", "sound", "play", "fawn"], c: 3 },
            { q: "The rose is a pretty ___. / The water began to ___.", opts: ["spring", "flower", "well", "bloom"], c: 1 },
            { q: "The ___ is where birds live. / ___ your toys in the box.", opts: ["tree", "nest", "place", "rest"], c: 1 },
            { q: "Use a ___ to measure. / The king is a fair ___.", opts: ["stick", "ruler", "line", "man"], c: 1 },
            { q: "I will ___ the door. / We are very ___ friends.", opts: ["shut", "close", "near", "open"], c: 1 },
            { q: "A ___ of water. / Do not ___ your ice cream.", opts: ["drop", "cup", "melt", "spill"], c: 0 },
            { q: "The ___ of the book is long. / Do not ___ the flower.", opts: ["page", "story", "pick", "read"], c: 2 },
            { q: "A cold ___ blew in. / ___ the string around.", opts: ["wind", "breeze", "air", "turn"], c: 0 },
            { q: "The ___ of the pencil is sharp. / He is the ___ of the team.", opts: ["tip", "point", "lead", "end"], c: 2 },
            { q: "I will ___ for my food. / A ___ is a small bird.", opts: ["pay", "bill", "check", "duck"], c: 1 },
            { q: "The ___ is a heavy metal. / I will ___ the group.", opts: ["iron", "lead", "gold", "silver"], c: 1 },
            { q: "I will ___ the present. / The ___ is here now.", opts: ["gift", "present", "now", "box"], c: 1 }
        ]
    },
    {
        title: "Lesson 4: Compound Words",
        instr: "Two words joined together.",
        qs: [
            { q: "sun + flower =", opts: ["sunshine", "flowerpot", "sunflower", "garden"], c: 2 },
            { q: "rain + bow =", opts: ["rainbow", "raincoat", "raindrop", "snowbow"], c: 0 },
            { q: "butter + fly =", opts: ["buttercup", "butterfly", "flybutter", "dragonfly"], c: 1 },
            { q: "back + pack =", opts: ["backpack", "package", "backside", "backyard"], c: 0 },
            { q: "star + fish =", opts: ["starfish", "fishstar", "starry", "fishing"], c: 0 },
            { q: "cow + boy =", opts: ["cowgirl", "cowboy", "cattle", "horseman"], c: 1 },
            { q: "cup + cake =", opts: ["cupcake", "pancake", "bake", "sweet"], c: 0 },
            { q: "mail + box =", opts: ["mailbox", "mailman", "post", "letter"], c: 0 },
            { q: "snow + man =", opts: ["snowball", "snowman", "snowy", "winter"], c: 1 },
            { q: "bed + room =", opts: ["bedroom", "bedspread", "sleep", "house"], c: 0 },
            { q: "basket + ball =", opts: ["football", "basketball", "hoop", "game"], c: 1 },
            { q: "tooth + brush =", opts: ["toothpaste", "toothbrush", "teeth", "clean"], c: 1 },
            { q: "pan + cake =", opts: ["cupcake", "pancake", "breakfast", "bread"], c: 1 },
            { q: "fire + fly =", opts: ["fireman", "firefly", "bug", "light"], c: 1 },
            { q: "jelly + fish =", opts: ["starfish", "jellyfish", "ocean", "swim"], c: 1 },
            { q: "day + dream =", opts: ["nightmare", "daydream", "sleep", "think"], c: 1 },
            { q: "pop + corn =", opts: ["popcorn", "soda", "kernel", "snack"], c: 0 },
            { q: "earth + quake =", opts: ["earthquake", "shaking", "ground", "dirt"], c: 0 },
            { q: "key + board =", opts: ["piano", "keyboard", "computer", "typing"], c: 1 },
            { q: "hand + shake =", opts: ["handshake", "greeting", "wave", "hello"], c: 0 },
            { q: "light + house =", opts: ["lighthouse", "lamp", "tower", "ocean"], c: 0 },
            { q: "note + book =", opts: ["paper", "notebook", "writing", "school"], c: 1 },
            { q: "sand + castle =", opts: ["sandcastle", "beach", "tower", "sand"], c: 0 },
            { q: "skate + board =", opts: ["roller", "skateboard", "wheels", "ride"], c: 1 },
            { q: "sun + burn =", opts: ["sunlight", "sunburn", "hot", "beach"], c: 1 },
            { q: "table + cloth =", opts: ["napkin", "tablecloth", "fabric", "dinner"], c: 1 },
            { q: "under + water =", opts: ["underwater", "ocean", "swim", "wet"], c: 0 },
            { q: "wheel + chair =", opts: ["bicycle", "wheelchair", "ride", "seat"], c: 1 },
            { q: "dragon + fly =", opts: ["butterfly", "dragonfly", "bug", "wing"], c: 1 },
            { q: "door + bell =", opts: ["doorbell", "knock", "ring", "house"], c: 0 },
            { q: "ear + ring =", opts: ["earring", "jewelry", "earlobe", "gold"], c: 0 },
            { q: "foot + ball =", opts: ["soccer", "football", "sport", "game"], c: 1 }
        ]
    },
    {
        title: "Lesson 5: Plural Nouns",
        instr: "More than one!",
        qs: [
            { q: "One dog, many ___", opts: ["doges", "dogs", "dogging", "dogly"], c: 1 },
            { q: "One cat, many ___", opts: ["cats", "cates", "catty", "catted"], c: 0 },
            { q: "One box, many ___", opts: ["boxs", "boxes", "boxing", "boxly"], c: 1 },
            { q: "One dish, many ___", opts: ["dishs", "dishes", "dished", "dishing"], c: 1 },
            { q: "One book, many ___", opts: ["bookes", "books", "booking", "bookly"], c: 1 },
            { q: "One pencil, many ___", opts: ["penciles", "pencils", "pencil", "pencilling"], c: 1 },
            { q: "One fox, many ___", opts: ["foxes", "foxs", "foxy", "foxing"], c: 0 },
            { q: "One bus, many ___", opts: ["buses", "buss", "busing", "busly"], c: 0 },
            { q: "One lunch, many ___", opts: ["lunchs", "lunches", "lunching", "lunched"], c: 1 },
            { q: "One brush, many ___", opts: ["brushs", "brushes", "brushing", "brushly"], c: 1 },
            { q: "One church, many ___", opts: ["churchs", "churches", "churchy", "churched"], c: 1 },
            { q: "One glass, many ___", opts: ["glasss", "glasses", "glassy", "glassing"], c: 1 },
            { q: "One kiss, many ___", opts: ["kisss", "kisses", "kissing", "kissed"], c: 1 },
            { q: "One potato, many ___", opts: ["potatos", "potatoes", "potatoed", "potatoly"], c: 1 },
            { q: "One tomato, many ___", opts: ["tomatos", "tomatoes", "tomatoing", "tomatosly"], c: 1 },
            { q: "One hero, many ___", opts: ["heros", "heroes", "heroic", "heroing"], c: 1 },
            { q: "One baby, many ___", opts: ["babys", "babies", "babying", "babied"], c: 1 },
            { q: "One city, many ___", opts: ["citys", "cities", "citying", "citied"], c: 1 },
            { q: "One lady, many ___", opts: ["ladys", "ladies", "ladying", "ladied"], c: 1 },
            { q: "One fly, many ___", opts: ["flys", "flies", "flying", "flied"], c: 1 },
            { q: "One puppy, many ___", opts: ["puppys", "puppies", "pupping", "pupped"], c: 1 },
            { q: "One leaf, many ___", opts: ["leafs", "leaves", "leafes", "leafy"], c: 1 },
            { q: "One knife, many ___", opts: ["knifes", "knives", "knifing", "knifed"], c: 1 },
            { q: "One wolf, many ___", opts: ["wolfs", "wolves", "wolfing", "wolfed"], c: 1 },
            { q: "One life, many ___", opts: ["lifes", "lives", "living", "lived"], c: 1 },
            { q: "One shelf, many ___", opts: ["shelfs", "shelves", "shelving", "shelfed"], c: 1 },
            { q: "One tree, many ___", opts: ["trees", "treees", "treeing", "treely"], c: 0 },
            { q: "One cup, many ___", opts: ["cups", "cupes", "cupping", "cuply"], c: 0 },
            { q: "One egg, many ___", opts: ["eggs", "egges", "egging", "eggy"], c: 0 },
            { q: "One ball, many ___", opts: ["balls", "balles", "balling", "bally"], c: 0 },
            { q: "One shoe, many ___", opts: ["shoes", "shoees", "shoeing", "shoely"], c: 0 },
            { q: "One toy, many ___", opts: ["toys", "toyes", "toying", "toyed"], c: 0 }
        ]
    },
    {
        title: "Lesson 6: Verbs",
        instr: "Find the action word.",
        qs: [
            { q: "The boy ___ to school.", opts: ["apple", "runs", "happy", "green"], c: 1 },
            { q: "I ___ a book every night.", opts: ["read", "blue", "pencil", "sleepy"], c: 0 },
            { q: "We ___ in the pool.", opts: ["swim", "water", "wet", "fish"], c: 0 },
            { q: "Birds ___ in the sky.", opts: ["fly", "cloud", "wings", "high"], c: 0 },
            { q: "She ___ a beautiful song.", opts: ["sings", "music", "loud", "happy"], c: 0 },
            { q: "The frog ___ into the pond.", opts: ["jumps", "green", "water", "wet"], c: 0 },
            { q: "He ___ his milk.", opts: ["drinks", "glass", "white", "cold"], c: 0 },
            { q: "My dad ___ the car.", opts: ["drives", "road", "fast", "red"], c: 0 },
            { q: "We ___ our lunch at noon.", opts: ["eat", "food", "yummy", "bread"], c: 0 },
            { q: "The baby ___ all night.", opts: ["sleeps", "bed", "tired", "quiet"], c: 0 },
            { q: "The cat ___ the mouse.", opts: ["chased", "tail", "fast", "furry"], c: 0 },
            { q: "I ___ with my pencil.", opts: ["write", "paper", "yellow", "eraser"], c: 0 },
            { q: "She ___ a pretty picture.", opts: ["draws", "crayons", "art", "blue"], c: 0 },
            { q: "They ___ in the park.", opts: ["play", "slide", "fun", "grass"], c: 0 },
            { q: "The wind ___ through the trees.", opts: ["blows", "cold", "leaf", "air"], c: 0 },
            { q: "He ___ the ball to me.", opts: ["throws", "catch", "round", "play"], c: 0 },
            { q: "I ___ to my teacher.", opts: ["listen", "ear", "school", "quiet"], c: 0 },
            { q: "She ___ for the bus.", opts: ["waits", "stop", "yellow", "late"], c: 0 },
            { q: "We ___ up the stairs.", opts: ["climb", "high", "step", "house"], c: 0 },
            { q: "The sun ___ in the morning.", opts: ["shines", "hot", "yellow", "sky"], c: 0 },
            { q: "He ___ a funny joke.", opts: ["tells", "laugh", "happy", "silly"], c: 0 },
            { q: "I ___ my room.", opts: ["clean", "neat", "bed", "closet"], c: 0 },
            { q: "The dog ___ loudly.", opts: ["barks", "tail", "furry", "brown"], c: 0 },
            { q: "We ___ on the floor.", opts: ["sit", "chair", "rug", "down"], c: 0 },
            { q: "The horse ___ fast.", opts: ["gallops", "ride", "farm", "brown"], c: 0 },
            { q: "She ___ her hair.", opts: ["brushes", "mirror", "pretty", "long"], c: 0 },
            { q: "He ___ a tall tower.", opts: ["builds", "blocks", "high", "play"], c: 0 },
            { q: "I ___ my new shoes.", opts: ["wear", "feet", "socks", "blue"], c: 0 },
            { q: "The fish ___ in the sea.", opts: ["swim", "water", "scales", "wet"], c: 0 },
            { q: "They ___ to the store.", opts: ["walk", "road", "shoes", "near"], c: 0 },
            { q: "He ___ at the funny clown.", opts: ["laughs", "smile", "silly", "joke"], c: 0 },
            { q: "The rain ___ on the roof.", opts: ["falls", "water", "wet", "cloud"], c: 0 }
        ]
    },
    {
        title: "Lesson 7: Adjectives",
        instr: "Words that describe things.",
        qs: [
            { q: "The ___ apple was yummy.", opts: ["run", "red", "eat", "fast"], c: 1 },
            { q: "The puppy is very ___.", opts: ["jump", "cute", "bark", "tail"], c: 1 },
            { q: "It was a ___ day.", opts: ["sun", "sunny", "sky", "blue"], c: 1 },
            { q: "I have a ___ ball.", opts: ["round", "spin", "bounce", "play"], c: 0 },
            { q: "The elephant is ___.", opts: ["tiny", "huge", "small", "thin"], c: 1 },
            { q: "The lemon is ___.", opts: ["sweet", "sour", "blue", "salty"], c: 1 },
            { q: "The kitten has ___ fur.", opts: ["soft", "bark", "run", "meow"], c: 0 },
            { q: "The car went down the ___ road.", opts: ["fast", "long", "drive", "wheel"], c: 1 },
            { q: "I wore a ___ shirt.", opts: ["blue", "wear", "pants", "closet"], c: 0 },
            { q: "The giant was very ___.", opts: ["tall", "short", "tiny", "little"], c: 0 },
            { q: "The soup was very ___.", opts: ["cold", "hot", "ice", "frozen"], c: 1 },
            { q: "The bunny is ___.", opts: ["loud", "quiet", "noisy", "scream"], c: 1 },
            { q: "The rock is ___.", opts: ["hard", "soft", "fluffy", "squishy"], c: 0 },
            { q: "The ice cream is ___.", opts: ["hot", "cold", "warm", "spicy"], c: 1 },
            { q: "She has ___ hair.", opts: ["long", "walk", "sing", "head"], c: 0 },
            { q: "The monster was ___.", opts: ["scary", "nice", "kind", "funny"], c: 0 },
            { q: "The candy is ___.", opts: ["sweet", "sour", "bitter", "salty"], c: 0 },
            { q: "The bed is ___.", opts: ["hard", "comfy", "wood", "floor"], c: 1 },
            { q: "The clown was ___.", opts: ["sad", "funny", "mad", "angry"], c: 1 },
            { q: "The sky is ___.", opts: ["green", "blue", "red", "purple"], c: 1 },
            { q: "The turtle is ___.", opts: ["fast", "slow", "quick", "speedy"], c: 1 },
            { q: "The sun is ___.", opts: ["bright", "dark", "dim", "black"], c: 0 },
            { q: "The pillow is ___.", opts: ["hard", "soft", "heavy", "rough"], c: 1 },
            { q: "The diamond is ___.", opts: ["shiny", "dull", "dirty", "old"], c: 0 },
            { q: "The mouse is ___.", opts: ["big", "small", "huge", "tall"], c: 1 },
            { q: "The rain makes things ___.", opts: ["dry", "wet", "hot", "dusty"], c: 1 },
            { q: "The cake was ___.", opts: ["yummy", "bad", "bitter", "sour"], c: 0 },
            { q: "He is a ___ boy.", opts: ["kind", "run", "jump", "play"], c: 0 },
            { q: "The stars are ___.", opts: ["pretty", "dark", "ground", "near"], c: 0 },
            { q: "The music was ___.", opts: ["loud", "see", "smell", "blue"], c: 0 },
            { q: "The box is ___.", opts: ["empty", "full", "heavy", "all of these"], c: 3 },
            { q: "The grass is ___.", opts: ["pink", "green", "blue", "red"], c: 1 }
        ]
    },
    {
        title: "Lesson 8: Proper Nouns",
        instr: "Special names for people and places.",
        qs: [
            { q: "Which is a special name?", opts: ["boy", "girl", "Merola", "friend"], c: 2 },
            { q: "Which is a special place?", opts: ["school", "Egypt", "park", "store"], c: 1 },
            { q: "Which is a day of the week?", opts: ["today", "Monday", "morning", "night"], c: 1 },
            { q: "Which is a month?", opts: ["winter", "July", "summer", "week"], c: 1 },
            { q: "Which is a name for a cat?", opts: ["kitten", "Whiskers", "animal", "pet"], c: 1 },
            { q: "Which is a city?", opts: ["town", "London", "village", "street"], c: 1 },
            { q: "Which is a country?", opts: ["land", "Canada", "place", "state"], c: 1 },
            { q: "Which is a holiday?", opts: ["party", "Christmas", "day", "gift"], c: 1 },
            { q: "Which is a special planet?", opts: ["star", "Mars", "moon", "sun"], c: 1 },
            { q: "Which is a name for a teacher?", opts: ["woman", "Mrs. Smith", "person", "lady"], c: 1 },
            { q: "Which is a day?", opts: ["tomorrow", "Friday", "yesterday", "soon"], c: 1 },
            { q: "Which is a month?", opts: ["October", "autumn", "fall", "season"], c: 0 },
            { q: "Which is a name for a dog?", opts: ["puppy", "Fido", "canine", "friend"], c: 1 },
            { q: "Which is a special mountain?", opts: ["hill", "Mount Everest", "rock", "stone"], c: 1 },
            { q: "Which is a ocean?", opts: ["water", "Pacific Ocean", "river", "lake"], c: 1 },
            { q: "Which is a person's name?", opts: ["man", "David", "boy", "sir"], c: 1 },
            { q: "Which is a street name?", opts: ["road", "Main Street", "path", "lane"], c: 1 },
            { q: "Which is a state?", opts: ["country", "Texas", "land", "area"], c: 1 },
            { q: "Which is a month?", opts: ["January", "winter", "cold", "snow"], c: 0 },
            { q: "Which is a day?", opts: ["Sunday", "weekend", "time", "hour"], c: 0 },
            { q: "Which is a name for a queen?", opts: ["lady", "Queen Elizabeth", "woman", "leader"], c: 1 },
            { q: "Which is a lake?", opts: ["water", "Lake Michigan", "pond", "stream"], c: 1 },
            { q: "Which is a name for a boy?", opts: ["friend", "Sam", "brother", "son"], c: 1 },
            { q: "Which is a name for a girl?", opts: ["sister", "Lily", "daughter", "child"], c: 1 },
            { q: "Which is a special building?", opts: ["house", "White House", "store", "office"], c: 1 },
            { q: "Which is a school name?", opts: ["building", "Lincoln School", "place", "class"], c: 1 },
            { q: "Which is a holiday?", opts: ["Easter", "bunny", "egg", "spring"], c: 0 },
            { q: "Which is a month?", opts: ["May", "spring", "flower", "warm"], c: 0 },
            { q: "Which is a day?", opts: ["Wednesday", "middle", "week", "work"], c: 0 },
            { q: "Which is a restaurant?", opts: ["food", "Burger King", "place", "eat"], c: 1 },
            { q: "Which is a name for a car?", opts: ["vehicle", "Toyota", "ride", "wheels"], c: 1 },
            { q: "Which is a name for a book?", opts: ["story", "Cinderella", "pages", "read"], c: 1 }
        ]
    },
    {
        title: "Lesson 9: Contractions",
        instr: "Shortening words.",
        qs: [
            { q: "do + not =", opts: ["don't", "dont", "do'not", "doit"], c: 0 },
            { q: "is + not =", opts: ["isnt", "isn't", "isnot", "is't"], c: 1 },
            { q: "I + am =", opts: ["Iam", "I'm", "Im", "I'am"], c: 1 },
            { q: "can + not =", opts: ["cant", "can't", "cannot", "can'tnot"], c: 1 },
            { q: "it + is =", opts: ["itis", "it's", "its", "it'is"], c: 1 },
            { q: "he + is =", opts: ["heis", "he's", "hes", "he'is"], c: 1 },
            { q: "she + is =", opts: ["sheis", "she's", "shes", "she'is"], c: 1 },
            { q: "we + are =", opts: ["weare", "we're", "were", "we'ar"], c: 1 },
            { q: "they + are =", opts: ["theyare", "they're", "there", "they'r"], c: 1 },
            { q: "you + are =", opts: ["youare", "you're", "your", "you'r"], c: 1 },
            { q: "was + not =", opts: ["wasnt", "was'nt", "wasnot", "was'n"], c: 1 },
            { q: "were + not =", opts: ["werent", "were'nt", "werenot", "were'n"], c: 1 },
            { q: "have + not =", opts: ["havent", "haven't", "havenot", "hav'not"], c: 1 },
            { q: "has + not =", opts: ["hasnt", "has'nt", "hasnot", "has'n"], c: 1 },
            { q: "will + not =", opts: ["willnt", "won't", "wont", "will'not"], c: 1 },
            { q: "did + not =", opts: ["didnt", "didn't", "didnot", "did'n"], c: 1 },
            { q: "could + not =", opts: ["couldnt", "couldn't", "couldnot", "could'nt"], c: 1 },
            { q: "would + not =", opts: ["wouldnt", "wouldn't", "wouldnot", "would'nt"], c: 1 },
            { q: "should + not =", opts: ["shouldnt", "shouldn't", "shouldnot", "should'nt"], c: 1 },
            { q: "I + will =", opts: ["Iwill", "I'll", "Ill", "I'wl"], c: 1 },
            { q: "you + will =", opts: ["youwill", "you'll", "youll", "you'l"], c: 1 },
            { q: "he + will =", opts: ["hewill", "he'll", "hell", "he'l"], c: 1 },
            { q: "she + will =", opts: ["shewill", "she'll", "shell", "she'l"], c: 1 },
            { q: "we + will =", opts: ["wewill", "we'll", "well", "we'l"], c: 1 },
            { q: "they + will =", opts: ["theywill", "they'll", "theyll", "they'l"], c: 1 },
            { q: "I + have =", opts: ["Ihave", "I've", "Ive", "I'v"], c: 1 },
            { q: "you + have =", opts: ["youhave", "you've", "youve", "you'v"], c: 1 },
            { q: "we + have =", opts: ["wehave", "we've", "weve", "we'v"], c: 1 },
            { q: "they + have =", opts: ["theyhave", "they've", "theyve", "they'v"], c: 1 },
            { q: "let + us =", opts: ["letus", "let's", "lets", "let'is"], c: 1 },
            { q: "there + is =", opts: ["thereis", "there's", "theres", "there'is"], c: 1 },
            { q: "that + is =", opts: ["thatis", "that's", "thats", "that'is"], c: 1 }
        ]
    },
    {
        title: "Lesson 10: Rhyming Words",
        instr: "Words that sound the same at the end.",
        qs: [
            { q: "What rhymes with <u>cat</u>?", opts: ["dog", "bat", "bird", "fish"], c: 1 },
            { q: "What rhymes with <u>tree</u>?", opts: ["bee", "leaf", "green", "wood"], c: 0 },
            { q: "What rhymes with <u>sun</u>?", opts: ["hot", "fun", "day", "star"], c: 1 },
            { q: "What rhymes with <u>cake</u>?", opts: ["pie", "bake", "sweet", "eat"], c: 1 },
            { q: "What rhymes with <u>dog</u>?", opts: ["cat", "log", "pet", "fur"], c: 1 },
            { q: "What rhymes with <u>pig</u>?", opts: ["dig", "cow", "mud", "pen"], c: 0 },
            { q: "What rhymes with <u>blue</u>?", opts: ["red", "shoe", "sky", "green"], c: 1 },
            { q: "What rhymes with <u>rain</u>?", opts: ["cloud", "train", "wet", "drop"], c: 1 },
            { q: "What rhymes with <u>bear</u>?", opts: ["pear", "lion", "forest", "fur"], c: 0 },
            { q: "What rhymes with <u>boat</u>?", opts: ["sail", "coat", "water", "sea"], c: 1 },
            { q: "What rhymes with <u>star</u>?", opts: ["car", "moon", "night", "sky"], c: 0 },
            { q: "What rhymes with <u>mouse</u>?", opts: ["cat", "house", "cheese", "hole"], c: 1 },
            { q: "What rhymes with <u>king</u>?", opts: ["ring", "crown", "queen", "gold"], c: 0 },
            { q: "What rhymes with <u>face</u>?", opts: ["race", "eye", "nose", "head"], c: 0 },
            { q: "What rhymes with <u>bell</u>?", opts: ["shell", "ring", "loud", "sound"], c: 0 },
            { q: "What rhymes with <u>book</u>?", opts: ["look", "read", "page", "story"], c: 0 },
            { q: "What rhymes with <u>day</u>?", opts: ["play", "sun", "night", "week"], c: 0 },
            { q: "What rhymes with <u>light</u>?", opts: ["night", "sun", "lamp", "dark"], c: 0 },
            { q: "What rhymes with <u>ball</u>?", opts: ["tall", "round", "play", "game"], c: 0 },
            { q: "What rhymes with <u>fly</u>?", opts: ["sky", "bug", "wing", "bird"], c: 0 },
            { q: "What rhymes with <u>bed</u>?", opts: ["red", "sleep", "rest", "night"], c: 0 },
            { q: "What rhymes with <u>fish</u>?", opts: ["dish", "water", "swim", "sea"], c: 0 },
            { q: "What rhymes with <u>frog</u>?", opts: ["hop", "log", "pond", "green"], c: 1 },
            { q: "What rhymes with <u>goat</u>?", opts: ["coat", "farm", "horn", "grass"], c: 0 },
            { q: "What rhymes with <u>hand</u>?", opts: ["sand", "fingers", "wave", "clap"], c: 0 },
            { q: "What rhymes with <u>ice</u>?", opts: ["mice", "cold", "water", "frozen"], c: 0 },
            { q: "What rhymes with <u>jar</u>?", opts: ["car", "lid", "jam", "glass"], c: 0 },
            { q: "What rhymes with <u>kite</u>?", opts: ["bite", "fly", "string", "wind"], c: 0 },
            { q: "What rhymes with <u>map</u>?", opts: ["cap", "road", "land", "way"], c: 0 },
            { q: "What rhymes with <u>nest</u>?", opts: ["best", "bird", "egg", "tree"], c: 0 },
            { q: "What rhymes with <u>old</u>?", opts: ["gold", "age", "young", "new"], c: 0 },
            { q: "What rhymes with <u>pan</u>?", opts: ["can", "cook", "hot", "kitchen"], c: 0 }
        ]
    }
];

