// readingData.js
const readingSentences = [
    "The brave dog ran to the park.",
    "A small bird sang a happy song.",
    "We like to eat sweet red apples.",
    "The big yellow sun is very hot.",
    "I can see a blue fish in the water.",
    "My mom made a big chocolate cake.",
    "The green grass is soft and wet.",
    "She has a pretty doll with a pink dress.",
    "We play with a round bouncy ball.",
    "The cat likes to sleep on the rug.",
    "I have five cents in my pocket.",
    "The school bus is bright and yellow.",
    "Do you want to play a fun game?",
    "The rain fell on the dry ground.",
    "A little mouse found some yellow cheese.",
    "We go to school to learn and play.",
    "The stars shine bright in the night sky.",
    "I like to read my favorite book.",
    "The tree has many green leaves.",
    "A fast rabbit hopped over the log.",
    "My teacher is very kind and smart.",
    "The honey bee sits on a flower.",
    "Wash your hands before you eat.",
    "The clock says it is time for lunch.",
    "I can jump over the little puddle.",
    "The brown cow eats green grass.",
    "Please sit down in your chair.",
    "The baby cry for a bottle of milk.",
    "We saw a large ship on the lake.",
    "I help my dad wash the white car.",
    "The snow is cold and very white.",
    "Brush your teeth every morning.",
    "The fire is hot and glows orange.",
    "He wore a warm coat in the wind.",
    "The farm has many loud ducks.",
    "I love to swing high at the park.",
    "The turtle walks very slowly.",
    "A spider made a web on the wall.",
    "We use a fork to eat our dinner.",
    "The moon is round and white.",
    "I found a shiny rock in the sand.",
    "The elephant is very big and gray.",
    "Wear your hat when it is sunny.",
    "The lion has a very loud roar.",
    "I like to draw with my crayons.",
    "The soup is in a blue bowl.",
    "We walk to the store for milk.",
    "A butterfly has colorful wings.",
    "The frog jumped into the pond.",
    "I can write my name with a pen.",
    "The pig lives on a muddy farm.",
    "It is time to go to sleep now.",
    "The sky is very clear and blue.",
    "She has a brother and a sister.",
    "The candy is sweet and sticky.",
    "The dog barked at the mail man.",
    "We go to the beach in summer.",
    "The kite flew high in the clouds.",
    "A snail moves along the garden path.",
    "I have a new pair of shoes.",
    "The bread is fresh and soft.",
    "We watch the movie at home.",
    "The clock has two black hands.",
    "He can ride a bike very fast.",
    "The garden has many red roses.",
    "A whale lives in the deep ocean.",
    "I like to help my mother cook.",
    "The wind blew the leaves away.",
    "Put your toys in the big box.",
    "The orange juice is very cold.",
    "A monkey swings from the tree.",
    "I use a towel after my bath.",
    "The morning sun is very bright.",
    "We build a tall tower with blocks.",
    "The boat floats on the river.",
    "She lost her tooth today.",
    "The forest is full of tall trees.",
    "I saw a deer in the woods.",
    "The ice cream is very cold.",
    "We take a nap on the sofa.",
    "The owl stays awake at night.",
    "I can count to one hundred.",
    "The king wears a gold crown.",
    "We go for a walk in the woods.",
    "The sheep has thick white wool.",
    "I like to drink cold water.",
    "The train goes fast on the track.",
    "She has a smile on her face.",
    "The bird built a nest in the tree.",
    "We use an umbrella in the rain.",
    "The pizza has a lot of cheese.",
    "I can catch the ball with my hands.",
    "The goat ate the green plants.",
    "He found a bug on the leaf.",
    "The plane flies high in the air.",
    "We play in the park every day.",
    "The star is high in the sky.",
    "I have a red balloon in my hand.",
    "The horse runs across the field.",
    "Learning is a lot of fun!"
];
